python3 process.py --config ./ --dataset_id criteo_x4_001